language: node_js

node_js:
  - "4"
  - "6"
  - "8"
  - "9"

notifications:
  slack: norch:wLsHiXjnAH5BdtTq3qtAqGp7
  
before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
